import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });
dotenv.config();

const supabaseUrl = process.env.EXPO_PUBLIC_SUPABASE_URL || '';
const supabaseKey = process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY || '';
const supabase = createClient(supabaseUrl, supabaseKey);

const mockUsers = [
  { id: 'mock-prov-1', email: 'prov1@test.com', name: 'João Encanador', role: 'provider', phone: '31999999991' },
  { id: 'mock-prov-2', email: 'prov2@test.com', name: 'Maria Eletricista', role: 'provider', phone: '31999999992' },
  { id: 'mock-prov-3', email: 'prov3@test.com', name: 'Carlos Faxina', role: 'provider', phone: '31999999993' },
  { id: 'mock-prov-4', email: 'prov4@test.com', name: 'Ana Montagem', role: 'provider', phone: '31999999994' },
  { id: 'mock-prov-5', email: 'prov5@test.com', name: 'Pedro Pintor', role: 'provider', phone: '31999999995' },
];

const mockProviders = [
  { id: 'mock-prov-1', categories: ['plumbing'], base_price: 100, available: true, rating: 4.8, review_count: 12, latitude: -19.9208, longitude: -43.9378, balance: 0 },
  { id: 'mock-prov-2', categories: ['electrical'], base_price: 150, available: true, rating: 4.9, review_count: 25, latitude: -19.9228, longitude: -43.9398, balance: 0 },
  { id: 'mock-prov-3', categories: ['cleaning'], base_price: 80, available: true, rating: 4.7, review_count: 8, latitude: -19.9188, longitude: -43.9358, balance: 0 },
  { id: 'mock-prov-4', categories: ['assembly'], base_price: 120, available: true, rating: 4.6, review_count: 15, latitude: -19.9248, longitude: -43.9338, balance: 0 },
  { id: 'mock-prov-5', categories: ['painting'], base_price: 200, available: true, rating: 5.0, review_count: 5, latitude: -19.9218, longitude: -43.9408, balance: 0 },
];

async function run() {
  console.log('Inserting mock users...');
  for (const u of mockUsers) {
    const { data: authData, error: authError } = await supabase.auth.signUp({
      email: u.email,
      password: 'password123',
      options: { data: { name: u.name, role: u.role } }
    });
    
    if (authError) {
      console.log('Error creating user auth ' + u.email + ':', authError.message);
      // Wait, maybe the user already exists. Let's try to sign in
      await supabase.auth.signInWithPassword({ email: u.email, password: 'password123' });
    }
    
    const sessionRes = await supabase.auth.getSession();
    const uid = authData?.user?.id || sessionRes.data?.session?.user?.id;
    
    if (uid) {
      // Upsert into public.users
      const { error: publicError } = await supabase.from('users').upsert({
        id: uid, // PK é id no banco, não uid
        name: u.name,
        email: u.email,
        phone: u.phone,
        role: u.role,
        photo_url: 'https://i.pravatar.cc/150?u=' + uid
      });
      if (publicError) console.error('Error in public.users', publicError.message);
      else console.log('User created:', u.email, uid);
    }
  }

  // We need the actual IDs generated by auth.signUp to insert into providers
  const { data: usersData, error: usersError } = await supabase.from('users').select('*');
  if (usersError) {
    console.error('Error fetching users:', usersError);
    return;
  }

  console.log('Inserting mock providers...');
  for (const mp of mockProviders) {
    // Find the corresponding user by matching the prefix
    const emailPrefix = 'prov' + mp.id.split('-')[2];
    const user = usersData.find((u: any) => u.email && u.email.startsWith(emailPrefix));
    if (user) {
      // Autentica como o usuário para passar pela política RLS (Row Level Security)
      await supabase.auth.signInWithPassword({ email: user.email, password: 'password123' });
      
      const { error } = await supabase.from('providers').upsert({
        id: user.id, // a tabela users no banco real usa id, não uid
        categories: mp.categories,
        base_price: mp.base_price,
        available: mp.available,
        rating: mp.rating,
        review_count: mp.review_count,
        latitude: mp.latitude,
        longitude: mp.longitude,
        balance: mp.balance
      });
      if (error) {
        console.error('Error upserting provider ' + user.id + ':', error.message);
      } else {
        console.log('Inserted provider for user', user.email);
      }
    } else {
      console.log('Could not find user for provider mock:', mp.id);
    }
  }
  console.log('Done!');
}

run();
